### ISSUE TITLE
[feature request] disable HTTP; use HTTPS only

### ISSUE THREAD

**Issue by shantanugadgil** [udhos/gowebhello#1]
In the current cmd set, when I only use HTTPS (parameter -httpsAddr), the `-addr` parameter is assumed to be `8080`.

This becomes a problem when I have to launch multiple HTTPS gowebhellos to simulate multiple HTTPS services on one machine.

For now,
1. I have just added a large number (20000) to the HTTPS port and used that for HTTP port value. (to keep gowebhello happy), so that the HTTP ports are outside any real usable port range.
2. Another solution I tried out was specifying ':0' as the `-addr` parameter; random port gets used.

Regards,
Shantanu

**Comment by udhos** [comment]
Currently you can run HTTPS-only by giving the same port to both -addr and -httpsAddr.
Please let me know if this solves your issue or not.

Example:

    $ ~/go/bin/gowebhello -addr :8443 -httpsAddr :8443
    2017/06/08 10:37:33 registering static directory /home/lab/go/src/github.com/udhos/gowebhello as www path /www/
    2017/06/08 10:37:33 serving on port TCP HTTP=:8443 HTTPS=:8443 TLS=true

**Comment by shantanugadgil** [comment]
😁 
I didn't think of that, If that works, I am ok with such a thing. 👍

**Comment by udhos** [comment]
@shantanugadgil I am closing this, please reopen if you find any difficulty.

**Comment by shantanugadgil** [comment]
This works fine, thanks! 🥇
