### ISSUE TITLE
[feature request] show HTTP headers

### ISSUE THREAD

**Issue by shantanugadgil** [udhos/gowebhello#3]
Would it be possible to add a flag to dump the HTTP headers being sent by the client?

This would come in handy while testing what headers a third party proxy/AWS ALB/NGINX is sending.
Thanks and Regards,
Shantanu Gadgil

**Comment by udhos** [comment]
Please have a look at this commit: https://github.com/udhos/gowebhello/commit/1dfb4259fad2be8dfe26a452848756d761e3e5bf

**Comment by shantanugadgil** [comment]
This works, thanks!!!
